/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.projeto_1.view;

import br.com.projeto_1.dao.TransporteDAO;
import br.com.projeto_1.dto.AlunoDTO;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.projeto_1.dto.InscricaoDTO;
import br.com.projeto_1.ctr.InscricaoCTR;
import br.com.projeto_1.dao.PontoEmbarqueDAO;

/**
 *
 * @author leonardo-teixeira
 */
public class AreaAlunoVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form AreaAlunoVIEW
     */
    private AlunoDTO alunoDTO;

    public AreaAlunoVIEW() {
        initComponents();
    }

    public void setPosicao() {
        if (this.getDesktopPane() != null) {
            int x = (this.getDesktopPane().getWidth() - this.getWidth()) / 2;
            int y = (this.getDesktopPane().getHeight() - this.getHeight()) / 2;
            this.setLocation(x, y);
        }
    }

    public AreaAlunoVIEW(AlunoDTO alunoDTO) {
        initComponents();
        this.alunoDTO = alunoDTO;
        tabelaTransporte.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaTransporte.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaTransporte.getColumnModel().getColumn(0).setWidth(0);
        String[] colunas = {"ID", "Placa", "Tipo", "Horário", "Capacidade", "Ponto"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
        tabelaTransporte.setModel(modelo);
        preencherTabela();
        setPosicao();

        System.out.println("Aluno logado: " + alunoDTO.getNome());

    }

    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaTransporte.getModel();
        modelo.setRowCount(0);

        PontoEmbarqueDAO dao = new PontoEmbarqueDAO();
        List<Object[]> linhas = dao.listarTransportesComPontos();

        for (Object[] linha : linhas) {
            modelo.addRow(linha); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTransporte = new javax.swing.JTable();
        btnInscrever = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("Área do  Aluno");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
        jLabel2.setText("Vizualização de Transportes");

        tabelaTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Tipo", "Horario", "Capacidade", "Ponto de Embarque"
            }
        ));
        tabelaTransporte.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaTransporteAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelaTransporte.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                tabelaTransporteComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaTransporte);

        btnInscrever.setBackground(new java.awt.Color(0, 204, 0));
        btnInscrever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1564491_add_create_new_plus_icon(1).png"))); // NOI18N
        btnInscrever.setText("Inscrever-se");
        btnInscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscreverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(368, 368, 368))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnInscrever)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnInscrever)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscreverActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaTransporte.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idTransporte = Integer.parseInt(tabelaTransporte.getValueAt(linhaSelecionada, 0).toString());

            InscricaoDTO inscricaoDTO = new InscricaoDTO();
            inscricaoDTO.setId_transporte(idTransporte);
            inscricaoDTO.setProntuario(alunoDTO.getProntuario());

            InscricaoCTR inscricaoCTR = new InscricaoCTR();
            boolean sucesso = inscricaoCTR.registrarInscricao(inscricaoDTO);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Inscricao confirmada!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao confirmar Inscricao!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um transporte para se inscrever.");
        }
    }//GEN-LAST:event_btnInscreverActionPerformed

    private void tabelaTransporteComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelaTransporteComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaTransporteComponentHidden

    private void tabelaTransporteAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaTransporteAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaTransporteAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscrever;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTransporte;
    // End of variables declaration//GEN-END:variables

}
